

CREATE TABLE MV_GENRE 
(
GENRE_ID INTEGER NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);

CREATE GENERATOR MV_GENRE_GEN;

CREATE TABLE MV_MOVIE
(
	MOVIE_ID INTEGER NOT NULL PRIMARY KEY,
	TITLE VARCHAR(200) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	STORYLINE BLOB SUB_TYPE TEXT,
	RELEASE_YEAR INTEGER,
	RELEASE_DATE TIMESTAMP,
	RUNTIME INTEGER,
	KIND INTEGER DEFAULT 1 NOT NULL,
	GENRE_ID INTEGER
);
ALTER TABLE MV_MOVIE ADD CONSTRAINT FK_MOVIE_GENREID FOREIGN KEY (GENRE_ID) REFERENCES MV_GENRE(GENRE_ID);
CREATE GENERATOR MV_MOVIE_GEN;

commit transaction;

SET TERM ^ ;

CREATE TRIGGER MV_MOVIE_TRG FOR MV_MOVIE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.MOVIE_ID IS NULL) THEN
        NEW.MOVIE_ID = GEN_ID(MV_MOVIE_GEN, 1);
END^

CREATE TRIGGER MV_GENRE_TRG FOR MV_GENRE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.GENRE_ID IS NULL) THEN
        NEW.GENRE_ID = GEN_ID(MV_GENRE_GEN, 1);
END^


set term ; ^

COMMIT TRANSACTION;
